asset_path: /home/user/mimic_distill_walk/source/legged_lab/legged_lab/assets/pcb_v2_description/mesh/530X6U_simple.stl
usd_dir: /home/user/mimic_distill_walk/source/legged_lab/legged_lab/assets/pcb_v2_description/mesh
usd_file_name: 530X6U_simple.usd
force_usd_conversion: true
make_instanceable: true
mass_props:
  mass: 1000.0
  density: null
rigid_props:
  rigid_body_enabled: null
  kinematic_enabled: null
  disable_gravity: null
  linear_damping: null
  angular_damping: null
  max_linear_velocity: null
  max_angular_velocity: null
  max_depenetration_velocity: null
  max_contact_impulse: null
  enable_gyroscopic_forces: null
  retain_accelerations: null
  solver_position_iteration_count: null
  solver_velocity_iteration_count: null
  sleep_threshold: null
  stabilization_threshold: null
collision_props:
  collision_enabled: true
  contact_offset: null
  rest_offset: null
  torsional_patch_radius: null
  min_torsional_patch_radius: null
mesh_collision_props:
  usd_func: pxr.UsdPhysics:MeshCollisionAPI
  physx_func: pxr.PhysxSchema:PhysxConvexDecompositionCollisionAPI
  mesh_approximation_name: convexDecomposition
  hull_vertex_limit: null
  max_convex_hulls: null
  min_thickness: null
  voxel_resolution: null
  error_percentage: null
  shrink_wrap: null
translation: !!python/tuple
- 0.0
- 0.0
- 0.0
rotation: !!python/tuple
- 1.0
- 0.0
- 0.0
- 0.0
scale: !!python/tuple
- 1.0
- 1.0
- 1.0
##
# Generated by MeshConverter on 2026-05-30 at 12:06:39.
##
