#!/usr/bin/env python3
"""Sideways TROTTING (diagonal) gait for the pcb_v2 wheeled quadruped.

This is a clean, parameterized re-statement of the gait that produced the frozen
reference trajectories ``examples/trajectory_trotting_acc_{,f}{005,01,015,02}.csv``.
Those were generated by ``quadruped_gaits_fwddyn.py``, which hardcodes one speed,
one direction and one output name inside a big multi-gait if/elif chain. Nothing
about the optimal-control problem changed here -- same stance, same knots, same
SolverIntro three-stage schedule -- only the plumbing, so this file can serve as
the base for further edits while ``quadruped_gaits_fwddyn.py`` stays frozen.

Trot = the two diagonal pairs swing alternately: (FR, RL) then (FL, RR). Because
each swing is balanced by its diagonal counterpart, the hips stay ~0 (|max| 3-7
deg) instead of adducting into the knock-knee (内八) that the single-leg-swing
tripod/walking gaits show. That symmetry is exactly why this gait is the clean
starting point.

Legacy naming: the reference CSVs encode speed as the decimals of the number
(0.05 -> ``005``, 0.1 -> ``01``) and prefix ``f`` (负) for the -Y direction.
This driver instead writes ``trajectory_trot_sideways_p3[_left]_v<speed>.csv`` so
it can never clobber a frozen baseline; pass ``--out`` to force another name.

Reproduction (2026-07-10, croco310 + build_conda): ``--pose legacy`` regenerates
``trajectory_trotting_acc_f005.csv`` to DDP-tolerance -- max |diff| 4.4e-3 rad on
a calf joint, 0.55 mm on the base. The references were solved on another machine
(different BLAS / an ODYN-enabled build), so bit-equality is not attainable. The
library's optional ``stateWeights``/``comWeights`` arguments (added for the tripod
drivers) are never passed here, so trot is bit-identical under the pre-tripod
library -- verified by swapping ``quadruped.py`` back to 8a6a027: max diff 0.0.

2026-07-10 pose change: ``--pose new`` is now the DEFAULT (front thigh -30 deg /
calf -30 deg, hind thigh 0 deg / calf +60 deg, base z 0.664888, pitch -45.70
deg), defined by the local ``Q0_NEW`` stance below.
``--pose legacy`` restores ``pcbWrapper.go_neutral()`` byte-for-byte. As with the
tripod driver the stance is injected HERE, not into ``pcb_v2/pcbWrapper.py``,
because ``go_neutral`` is shared by five other drivers that must keep the old one.

What the new stance forces (the legacy one, being exactly Y-symmetric with zero
roll/yaw, needed neither):
  * its quaternion is renormalized before use (norm is 4.7e-7 off); ``--pose
    legacy`` deliberately is NOT, so it still reproduces the committed CSVs;
  * it carries a small roll (-0.060 deg) and yaw (-1.000 deg), so a LEFT walk is
    seeded with the pose's Y-MIRROR (``--mirror-pose``, default auto). Without it
    the +Y walk would start from a stance yawed the SAME way as the -Y walk, which
    is a different gait rather than the mirror of it.

Direction note: ``createTrottingProblem`` always swings the (rfFoot, lhFoot)
diagonal first, so a LEFT walk additionally mirrors the foot-ROLE binding handed
to ``SimpleQuadrupedalGaitProblem`` (lf<->rf, lh<->rh). It then opens on the
(FL, RR) diagonal -- the exact Y-mirror of the right walk's (FR, RL) -- instead of
being merely a "handed" copy. Same trick as ``quadruped_walking_fwddyn.py``. The
frozen ``trajectory_trotting_acc_{005,01,...}.csv`` predate this and were pure
sign flips; on the Y-symmetric legacy stance that only cost a half-cycle phase
offset, which is why nobody noticed. Check with ``python _verify_mirror.py
<right.csv> <left.csv>``.

Run (from examples/, conda env croco310, build_conda on PYTHONPATH):
    python quadruped_trot_sideways.py                    # right (-Y) 0.05 m/s, new pose
    python quadruped_trot_sideways.py --speed 0.20       # right 0.20 m/s
    python quadruped_trot_sideways.py --direction left   # left (+Y), exact mirror
    python quadruped_trot_sideways.py --pose legacy      # the old go_neutral stance
    python quadruped_trot_sideways.py --display          # meshcat playback

Review the motion with:
    python plot.py <csv> --urdf pcb_v2/pcb_v2/urdf/pcb_v2.urdf --fps 100
"""
import argparse
import csv
import os
import signal
import time

import numpy as np
import pinocchio

import crocoddyl
from crocoddyl.utils.quadruped import SimpleQuadrupedalGaitProblem
from pcb_v2.pcbWrapper import pcb

signal.signal(signal.SIGINT, signal.SIG_DFL)
from pinocchio.robot_wrapper import RobotWrapper  # noqa: E402

FOOT = {"FL": "FL_foot_link", "FR": "FR_foot_link",
        "RL": "RL_foot_link", "RR": "RR_foot_link"}

parser = argparse.ArgumentParser()
parser.add_argument("--speed", type=float, default=0.05,
                    help="target average sideways speed (m/s); sets the per-cycle "
                         "stride = speed * cycle duration. Cadence is untouched.")
parser.add_argument("--direction", choices=["right", "left"], default="right",
                    help="right = -Y (the legacy 'f' prefix), left = +Y")
parser.add_argument("--cycles", type=int, default=8,
                    help="number of trot cycles, solved back to back")
parser.add_argument("--step-height", type=float, default=0.1,
                    help="swing-foot clearance target (m)")
parser.add_argument("--step-knots", type=int, default=35, help="nodes per swing phase")
parser.add_argument("--support-knots", type=int, default=5,
                    help="nodes per double-support phase")
parser.add_argument("--max-iters", type=int, default=100,
                    help="iteration cap for each of the three solve stages")
parser.add_argument("--pose", choices=["new", "legacy"], default="new",
                    help="'new' (default) = the 2026-07-10 stance in Q0_NEW; "
                         "'legacy' = pcbWrapper.go_neutral(), "
                         "the stance every trajectory_trotting_acc_* was solved from.")
parser.add_argument("--mirror-pose", choices=["auto", "on", "off"], default="auto",
                    help="Y-mirror the initial stance for a LEFT walk so it stays the exact "
                         "mirror of the RIGHT walk. auto = on iff --direction left. "
                         "A no-op on the legacy (Y-symmetric) pose.")
parser.add_argument("--out", type=str, default=None,
                    help="output CSV path; default includes a pose tag to avoid overwrites")
parser.add_argument("--display", action="store_true", help="loop the motion in meshcat")
args = parser.parse_args()

# timeStep is a fixed term of the 23-column CSV contract (downstream csv_to_npz.py
# reads it as 100 Hz). Change cadence through --step-knots/--support-knots instead.
TIME_STEP = 0.01

dir_path = os.path.dirname(os.path.realpath(__file__))
urdf_path = os.path.join(dir_path, "pcb_v2", "pcb_v2", "urdf", "pcb_v2.urdf")
mesh_dir = os.path.join(dir_path, "pcb_v2", "pcb_v2")

# 2026-07-10 stance (pinocchio order: base xyz, base quat xyzw, FL/FR/RL/RR x
# hip/thigh/calf). Front thigh/calf = -30/-30 deg, hind = 0/+60 deg.
Q0_NEW = np.array([
    0.0, 0.0, 0.664888,
    -0.00387392, -0.388313, -0.00824802, 0.921483,
    -1.78e-06, -0.523593, -0.523596,
    -4.59e-06, -0.523609, -0.523606,
    8.76624e-06, -1.88e-06, 1.04721,
    -2.47e-06, -1.36e-05, 1.04719,
])


def mirror_pose_y(q):
    """Reflect a configuration about the sagittal (XZ) plane, swapping L<->R legs.

    Under y -> -y: base y negates; the quaternion conjugates as (x,y,z,w) ->
    (-x,y,-z,w) (roll and yaw negate, pitch survives); the hip angles negate
    because the hip axis is +X, while thigh/calf ride on +Y and are unchanged.
    """
    qm = q.copy()
    qm[1] = -q[1]
    qm[3], qm[5] = -q[3], -q[5]
    FL, FR, RL, RR = slice(7, 10), slice(10, 13), slice(13, 16), slice(16, 19)
    qm[FL], qm[FR] = q[FR].copy(), q[FL].copy()
    qm[RL], qm[RR] = q[RR].copy(), q[RL].copy()
    for hip in (7, 10, 13, 16):
        qm[hip] = -qm[hip]
    return qm


robot = pcb()
robot_pcb = RobotWrapper.BuildFromURDF(urdf_path, mesh_dir)
model = robot_pcb.model

if args.pose == "legacy":
    # Passed through raw, quaternion and all: go_neutral's quat is 5.6e-5 off unit
    # norm, the solver renormalizes it internally, and reproducing the committed
    # CSVs exactly is the whole point of this branch.
    q0 = robot.go_neutral()
else:
    q0 = Q0_NEW.copy()
    q0[3:7] /= np.linalg.norm(q0[3:7])
mirror = args.mirror_pose == "on" or (args.mirror_pose == "auto" and args.direction == "left")
if mirror:
    q0 = mirror_pose_y(q0)
# q0 does triple duty: it seeds cycle 0, it fixes the contact geometry (each
# ContactModel3D pins a foot frame wherever FK(q0) puts it -- kp=0 in its Baumgarte
# gains, so there is no ground plane and no xref; the foot just stays put), and via
# referenceConfigurations["standing"] it becomes rmodel.defaultState, the stateReg
# target held at every node of every cycle. Set it BEFORE building the gait: the
# constructor snapshots defaultState and never reads the model attribute again.
model.referenceConfigurations["standing"] = q0
x0 = np.concatenate([q0, pinocchio.utils.zero(model.nv)])

# For LEFT, mirror the foot-ROLE binding too. createTrottingProblem hardcodes the
# (rfFoot, lhFoot) diagonal as the first swing pair, so swapping lf<->rf / lh<->rh
# makes the left walk open on (FL, RR) -- the Y-mirror of the right walk's (FR, RL)
# -- rather than on the same physical diagonal. Same trick as the walking driver.
if args.direction == "right":
    lf, rf, lh, rh = FOOT["FL"], FOOT["FR"], FOOT["RL"], FOOT["RR"]
else:
    lf, rf, lh, rh = FOOT["FR"], FOOT["FL"], FOOT["RR"], FOOT["RL"]
gait = SimpleQuadrupedalGaitProblem(model, lf, rf, lh, rh)

# One trot cycle = 2 x (double support + diagonal swing).
cycle_duration = 2 * (args.support_knots + args.step_knots) * TIME_STEP
stride = args.speed * cycle_duration
dir_sign = -1.0 if args.direction == "right" else 1.0
direction = (0.0, dir_sign)

out_path = args.out
if out_path is None:
    pose_tag = "p3_" if args.pose == "new" else "legacy_"
    dir_tag = "" if args.direction == "right" else "left_"
    out_path = "trajectory_trot_sideways_%s%sv%.2f.csv" % (pose_tag, dir_tag, args.speed)

print("trot %s (%+.0fY)  pose %s%s  speed %.3f m/s  stride %.4f m  cycle %.2f s  x%d" % (
    args.direction, dir_sign, args.pose, " (mirrored)" if mirror else "",
    args.speed, stride, cycle_duration, args.cycles))
print("opening diagonal: (%s, %s)" % (rf[:2], lh[:2]))

solver = [None] * args.cycles
for i in range(args.cycles):
    # gait.firstStep is True only on the first call, which halves the opening
    # stride so cycle 0 ramps in from standstill instead of lurching.
    solver[i] = crocoddyl.SolverIntro(
        gait.createTrottingProblem(
            x0, stride, args.step_height, TIME_STEP,
            args.step_knots, args.support_knots, direction=direction,
        )
    )
    solver[i].setCallbacks([crocoddyl.CallbackVerbose()])

    xs = [x0] * (solver[i].problem.T + 1)
    us = solver[i].problem.quasiStatic([x0] * solver[i].problem.T)
    # Three-stage schedule, warm-started in place: single/feasibility shooting
    # first, then full multiple shooting, then a hybrid split at T/3.
    solver[i].setDynamicsSolver(crocoddyl.DynamicsSolverType.FeasShoot)
    solver[i].solve(xs, us, args.max_iters, False)
    solver[i].setDynamicsSolver(crocoddyl.DynamicsSolverType.MultiShoot)
    solver[i].solve(xs, us, args.max_iters, False)
    solver[i].setDynamicsSolver(
        crocoddyl.DynamicsSolverType.HybridShoot, int(solver[i].problem.T / 3)
    )
    solver[i].solve(xs, us, args.max_iters, False)

    x0 = solver[i].xs[-1]   # next cycle starts where this one ended

joint_names = [model.names[i] for i in range(2, model.njoints)]
fieldnames = ["root_pos_x", "root_pos_y", "root_pos_z",
              "root_rot_x", "root_rot_y", "root_rot_z", "root_rot_w"] + joint_names + \
             ["FL_foot_joint", "FR_foot_joint", "RL_foot_joint", "RR_foot_joint"]
base_frame_id = model.getFrameId("Base_link")

rows = 0
base_xyz = []
with open(out_path, "w", newline="") as csvfile:
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    for solver_i in solver:
        for x in solver_i.xs:
            q = x[: model.nq]
            pinocchio.forwardKinematics(model, robot_pcb.data, q)
            pinocchio.updateFramePlacements(model, robot_pcb.data)
            base_pose = robot_pcb.data.oMf[base_frame_id]
            pos = base_pose.translation.copy()
            quat = pinocchio.SE3ToXYZQUAT(base_pose)[3:7]
            row = {"root_pos_x": pos[0], "root_pos_y": pos[1], "root_pos_z": pos[2],
                   "root_rot_x": quat[0], "root_rot_y": quat[1],
                   "root_rot_z": quat[2], "root_rot_w": quat[3]}
            for j, val in enumerate(q[7:]):
                row[joint_names[j]] = val
            for w in ("FL", "FR", "RL", "RR"):
                row[w + "_foot_joint"] = 0.0   # wheel joints are fixed in the URDF
            writer.writerow(row)
            base_xyz.append(pos)
            rows += 1

base_xyz = np.asarray(base_xyz)
travel = base_xyz[-1] - base_xyz[0]
duration = (rows - 1) * TIME_STEP
print("\nWrote %s: %d rows x %d cols" % (os.path.abspath(out_path), rows, len(fieldnames)))
print("base travel  dx %+.4f  dy %+.4f  dz %+.4f m   over %.2f s -> vy %+.4f m/s"
      % (travel[0], travel[1], travel[2], duration, travel[1] / duration))
print("base z range %.4f .. %.4f m" % (base_xyz[:, 2].min(), base_xyz[:, 2].max()))

if args.display:
    display = crocoddyl.MeshcatDisplay(robot_pcb)
    display.rate = -1
    display.freq = 1
    while True:
        for solver_i in solver:
            display.displayFromSolver(solver_i)
        time.sleep(1.0)
